package com.ajousw.spring.domain.navigation.api.provider;

import com.ajousw.spring.domain.navigation.api.info.route.NaverNavigationApiResponse;
import com.ajousw.spring.domain.navigation.api.info.route.NavigationApiResponse;
import com.ajousw.spring.domain.navigation.api.provider.factory.Provider;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

@Slf4j
@SpringBootTest
@ActiveProfiles("test")
class NaverNavigationTest {

    String dummy = "{\n"
            + "  \"code\": 0,\n"
            + "  \"message\": \"길찾기를 성공하였습니다.\",\n"
            + "  \"currentDateTime\": \"2024-01-06T23:42:14\",\n"
            + "  \"route\": {\n"
            + "    \"trafast\": [\n"
            + "      {\n"
            + "        \"summary\": {\n"
            + "          \"start\": {\n"
            + "            \"location\": [\n"
            + "              127.1053357,\n"
            + "              37.3522474\n"
            + "            ]\n"
            + "          },\n"
            + "          \"goal\": {\n"
            + "            \"location\": [\n"
            + "              127.1118746,\n"
            + "              37.345853\n"
            + "            ],\n"
            + "            \"dir\": 2\n"
            + "          },\n"
            + "          \"distance\": 1306,\n"
            + "          \"duration\": 299055,\n"
            + "          \"etaServiceType\": 0,\n"
            + "          \"departureTime\": \"2024-01-06T23:42:14\",\n"
            + "          \"bbox\": [\n"
            + "            [\n"
            + "              127.1053357,\n"
            + "              37.3458418\n"
            + "            ],\n"
            + "            [\n"
            + "              127.1120508,\n"
            + "              37.3522474\n"
            + "            ]\n"
            + "          ],\n"
            + "          \"tollFare\": 0,\n"
            + "          \"taxiFare\": 6240,\n"
            + "          \"fuelPrice\": 146\n"
            + "        },\n"
            + "        \"path\": [\n"
            + "          [\n"
            + "            127.1053436,\n"
            + "            37.3522474\n"
            + "          ],\n"
            + "          [\n"
            + "            127.105344,\n"
            + "            37.3521816\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1053442,\n"
            + "            37.3521266\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1053445,\n"
            + "            37.3520689\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1053452,\n"
            + "            37.3519455\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1053447,\n"
            + "            37.3516038\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1053487,\n"
            + "            37.3514822\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1053615,\n"
            + "            37.3514245\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1054249,\n"
            + "            37.3513833\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1055368,\n"
            + "            37.3513665\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1056373,\n"
            + "            37.3513659\n"
            + "          ],\n"
            + "          [\n"
            + "            127.106151,\n"
            + "            37.3513704\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1062966,\n"
            + "            37.3513708\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1063199,\n"
            + "            37.351251\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1063456,\n"
            + "            37.3508653\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1063615,\n"
            + "            37.3506247\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1063612,\n"
            + "            37.3502506\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1063612,\n"
            + "            37.350247\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1063611,\n"
            + "            37.3500613\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1064954,\n"
            + "            37.35006\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1069731,\n"
            + "            37.3500444\n"
            + "          ],\n"
            + "          [\n"
            + "            127.107994,\n"
            + "            37.3500181\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1086184,\n"
            + "            37.3500012\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1087088,\n"
            + "            37.3499988\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1088194,\n"
            + "            37.3499956\n"
            + "          ],\n"
            + "          [\n"
            + "            127.109017,\n"
            + "            37.3499944\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1091548,\n"
            + "            37.3499976\n"
            + "          ],\n"
            + "          [\n"
            + "            127.109227,\n"
            + "            37.3499987\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1092315,\n"
            + "            37.3499987\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1098525,\n"
            + "            37.3500125\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1108426,\n"
            + "            37.3500338\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1110672,\n"
            + "            37.3500381\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1118824,\n"
            + "            37.3500498\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120066,\n"
            + "            37.3500521\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120054,\n"
            + "            37.3498357\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120048,\n"
            + "            37.3495157\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120063,\n"
            + "            37.3494508\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120064,\n"
            + "            37.3494202\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120064,\n"
            + "            37.3494166\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120097,\n"
            + "            37.3492219\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120113,\n"
            + "            37.3491309\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120237,\n"
            + "            37.3486982\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120209,\n"
            + "            37.3481448\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120199,\n"
            + "            37.3481159\n"
            + "          ],\n"
            + "          [\n"
            + "            127.112019,\n"
            + "            37.3480681\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120231,\n"
            + "            37.3477238\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120233,\n"
            + "            37.3476824\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120222,\n"
            + "            37.3476643\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120285,\n"
            + "            37.3473227\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120309,\n"
            + "            37.3470812\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120325,\n"
            + "            37.3469775\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120433,\n"
            + "            37.3462006\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120478,\n"
            + "            37.3459951\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1120508,\n"
            + "            37.3458418\n"
            + "          ],\n"
            + "          [\n"
            + "            127.1118735,\n"
            + "            37.3458421\n"
            + "          ]\n"
            + "        ],\n"
            + "        \"section\": [\n"
            + "          {\n"
            + "            \"pointIndex\": 18,\n"
            + "            \"pointCount\": 16,\n"
            + "            \"distance\": 501,\n"
            + "            \"name\": \"돌마로\",\n"
            + "            \"congestion\": 3,\n"
            + "            \"speed\": 17\n"
            + "          },\n"
            + "          {\n"
            + "            \"pointIndex\": 33,\n"
            + "            \"pointCount\": 9,\n"
            + "            \"distance\": 151,\n"
            + "            \"name\": \"돌마로90번길\",\n"
            + "            \"congestion\": 0,\n"
            + "            \"speed\": 20\n"
            + "          },\n"
            + "          {\n"
            + "            \"pointIndex\": 41,\n"
            + "            \"pointCount\": 13,\n"
            + "            \"distance\": 317,\n"
            + "            \"name\": \"미금일로70번길\",\n"
            + "            \"congestion\": 3,\n"
            + "            \"speed\": 13\n"
            + "          }\n"
            + "        ],\n"
            + "        \"guide\": [\n"
            + "          {\n"
            + "            \"pointIndex\": 12,\n"
            + "            \"type\": 3,\n"
            + "            \"instructions\": \"'정자일로' 방면으로 우회전\",\n"
            + "            \"distance\": 175,\n"
            + "            \"duration\": 52232\n"
            + "          },\n"
            + "          {\n"
            + "            \"pointIndex\": 18,\n"
            + "            \"type\": 2,\n"
            + "            \"instructions\": \"머내공원사거리에서 '미금역' 방면으로 좌회전\",\n"
            + "            \"distance\": 146,\n"
            + "            \"duration\": 28280\n"
            + "          },\n"
            + "          {\n"
            + "            \"pointIndex\": 33,\n"
            + "            \"type\": 3,\n"
            + "            \"instructions\": \"'돌마로90번길' 방면으로 우회전\",\n"
            + "            \"distance\": 501,\n"
            + "            \"duration\": 103769\n"
            + "          },\n"
            + "          {\n"
            + "            \"pointIndex\": 53,\n"
            + "            \"type\": 3,\n"
            + "            \"instructions\": \"'서울·용인, 머내공원' 방면으로 우회전\",\n"
            + "            \"distance\": 468,\n"
            + "            \"duration\": 112032\n"
            + "          },\n"
            + "          {\n"
            + "            \"pointIndex\": 54,\n"
            + "            \"type\": 88,\n"
            + "            \"instructions\": \"목적지\",\n"
            + "            \"distance\": 16,\n"
            + "            \"duration\": 2742\n"
            + "          }\n"
            + "        ]\n"
            + "      }\n"
            + "    ]\n"
            + "  }\n"
            + "}";


    @Test
    void 파싱_테스트() {
        ObjectMapper mapper = new ObjectMapper();

        try {
            Map<String, Object> attributes = mapper.readValue(dummy, Map.class);
            NaverNavigationApiResponse naverNavigationPathInfo = new NaverNavigationApiResponse(attributes);
            log.info("{}", naverNavigationPathInfo.toString());
        } catch (JsonProcessingException | NullPointerException e) {
            log.error("으앙 주금 ㅋ", e);
        }
    }

    @Autowired
    private NavigationProvider navigationProvider;

    @Test
    void api_test() {
        Map<String, String> params = Map.of("start", "127.105336,37.352248", "goal",
                "127.11432998507473,37.378793096353206", "option", "trafast");
        NavigationApiResponse navigationQueryResult = navigationProvider.getNavigationQueryResult(Provider.NAVER,
                params);

        log.info("{}", navigationQueryResult);
    }
}